//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobAutoTemplate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SHLJS2M\\SQLEXPRESS2019;Initial Catalog=WolfApproveCore.tym-yp" +
            "mt;User ID=sa;Password=pass@word1;Connect Timeout=30;Encrypt=True;TrustServerCer" +
            "tificate=True")]
        public string WolfApproveCore_tym_ypmtConnectionString {
            get {
                return ((string)(this["WolfApproveCore_tym_ypmtConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-MTFBHTV\\SQLEXPRESS;Initial Catalog=WolfApproveCore.ypmt-prd;I" +
            "ntegrated Security=True;TrustServerCertificate=True")]
        public string WolfApproveCore_ypmt_prdConnectionString {
            get {
                return ((string)(this["WolfApproveCore_ypmt_prdConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-MTFBHTV\\SQLEXPRESS;Initial Catalog=WolfApproveCore.ypmt-prd;U" +
            "ser ID=sa;TrustServerCertificate=True")]
        public string WolfApproveCore_ypmt_prdConnectionString1 {
            get {
                return ((string)(this["WolfApproveCore_ypmt_prdConnectionString1"]));
            }
        }
    }
}
